[build]
  command = "pnpm install --no-frozen-lockfile && pnpm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"
  PINECONE_API_KEY = "pcsk_5xsDB9_BLQmPrXEqyAN6AL9tKdZGNf2eWVKbhY9pjhdSRaaFdaBE1kTr9AjVMV5Pgj3kYG"
  PINECONE_ASSISTANT_ID = "ad"
  PINECONE_PROJECT_ID = "d4916603-b265-4f6f-bca6-908ee716460c"
